@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_LEFT_RIGHT()

title System Component diagram for Ecommerce System

Component(web_app, "Web application for Admin","Component: Vuejs", "Run application code in web browser with AddProduct screen.")
ComponentDb(db, "Sneaker Shop Database","Component MySql", "Stores Products  ")

Boundary(System, "Ecommerce System") {
    Component(Controller, "AddProduct  Controller", "Component ASP.NET Controller", "Receive and process requests ")
    Component(Service, "Service","Component ASP.NET Service", "Bussiness logic to displaying AddProduct  ")
    Component(model, "Products Model", "Component ASP.NET Model", "Provide data  of Products model ")

    Rel(Controller, Service, "Uses")
    Rel(Service, model, "call model Product")
    Rel(model, db, "Write")
    Rel(web_app,Controller, "Make API call to [JSON/HTTPS]")
}
@enduml