@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title System Component diagram for Ecommerce System

Component(web_app, "Web application for Admin","Component: Vuejs", "Run application code in web browser with Login screen")
ComponentDb(db, "Sneaker Shop Database","Component: SQLServer", "Read data")

Boundary(System, "API Application") {
    Component(Controller, "AdminController", "Component: ASP.NET Controller", "Receive and process requests")
    Component(Service, "AdminService","Component: ASP.NET Service", "Bussines logic to check token and authenticate")
    Component(model, "AccountModel", "Component: ASP.NET Model", "Provide data  of account model ")

    Rel(Controller, Service, "Uses")
    Rel(Service, model, "Uses")
    Rel(model, db, "Read")
    Rel(web_app,Controller, "Make API call to [JSON/HTTPS]")
}
@enduml