@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title System Component diagram for Ecommerce System

Component(web_app, "Web application for Admin","Component: Vuejs", "Run application code in web browser with Categories  screen.")
ComponentDb(db, "Sneaker Shop Database","Component MySql", "Stores Categories ")

Boundary(System, "Ecommerce System") {
    Component(Controller, "Categories Controller", "Component ASP.NET Controller", "Receive and process requests ")
    Component(Service, "Service","Component ASP.NET Service", "Bussiness logic to displaying Categories  ")
    Component(model, "Categories  Model", "Component ASP.NET Model", "Provide data  of Categories  model ")

    Rel(Controller, Service, "Call")
    Rel(Service, model, "Call")
    Rel(model, db, "Delete")
    Rel(web_app,Controller, "Make API call to [JSON/HTTPS]")
}
@enduml