@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title System Component diagram for Ecommerce System

Component(web_app, "Web application for Admin","Component: Vuejs", "Run application code in web browser with Founders screen.")
ComponentDb(db, "Sneaker Shop Database","Component MySql", "Stores Founders")

Boundary(System, "Ecommerce System") {
    Component(Controller, "FoundersController", "Component ASP.NET Controller", "Receive and process requests ")
    Component(Service, "Service","Component ASP.NET Service", "Bussiness logic to displaying Founders ")
    Component(model, "Founders Model", "Component ASP.NET Model", "Provide data  of Founders model ")

    Rel(Controller, Service, "Call")
    Rel(Service, model, "Call")
    Rel(model, db, "Write")
    Rel(web_app,Controller, "Make API call to [JSON/HTTPS]")
}
@enduml